version: '3.9'

services:
  db:
    image: postgres:16
    container_name: petshop-api-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: petshop
    ports:
      - "5433:5432"   # Host:Container
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: petshop-api-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  db:
